# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

import os

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = 'Ascender CLI'
copyright = '2026, Ctrl IQ, Inc.'
author = 'Ascender Project Contributors'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['ascenderkit.cli.sphinx']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'classic'

# There are no custom static files to copy. Add the directory back to
# html_static_path if any are introduced; pointing at one that does not exist
# only produces a warning on every build.
html_static_path = []

rst_epilog = '''
.. |prog| replace:: ascender
'''

# -- Building without a server -----------------------------------------------

# reference.rst is generated by sphinxcontrib-autoprogram from the parser in
# ascenderkit.cli.sphinx, which is built by issuing an HTTP OPTIONS request per
# resource against a running Ascender. There is no static command table to fall
# back on: the CLI discovers its own commands the same way. So that one page is
# the only part of these docs that needs a server, and asking for it without one
# exits with a message naming ASCENDER_HOST.
#
# Rather than fail the whole build, drop the page when there are no credentials.
# The six hand-written pages then build offline, which is what CI does, and a
# build with ASCENDER_HOST set still produces the complete documentation.
#
# The toctree in index.rst names reference unconditionally. Moving that entry
# behind an `only` directive does not help, because toctree entries resolve
# while the source is read and `only` is evaluated later, so the warning is
# suppressed by name instead.
if not any(os.environ.get(prefix + 'HOST') for prefix in ('ASCENDER_', 'CONTROLLER_', 'TOWER_')):
    exclude_patterns = ['reference.rst']
    suppress_warnings = ['toc.excluded']
